# Generated by Django 5.0.6 on 2024-09-11 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_host_rename_created_at_room_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Host',
        ),
    ]
